#!/bin/bash

if [[ "$1" = "" || "$2" = "" ]]; then
    echo "Usage: new_day <year> <day>" >&2
    exit 1
fi

set -e
set -u
set -o pipefail

year=${1}
day_full=${2}
case ${day_full} in
    0*)
        day_no=${day_full:1}
        ;;
    *)
        day_no=${day_full}
        ;;
esac

mod="day${day_full}"
crate="year$year"
prefix="$crate/$mod"

mod_file="$crate/src/$mod.rs"
echo "$prefix: Creating \`$mod\` module for \`$crate\` crate."
cp template/dayXX.rs "$mod_file"

echo "$prefix: Replacing all occurrences of \`XX\` with \`$day_full\` in \`$mod_file\`."
sed -E -i "s/XX/$day_full/g" "$mod_file"

echo "$prefix: Replacing all occurrences of \`YYYY\` with \`$year\` in \`$mod_file\`."
sed -E -i "s/YYYY/$year/g" "$mod_file"

crate_file="$crate/src/lib.rs"
last_day_full=$(sed -E -n "s/.*day(0[1-9]|[12][0-9]).*/\1/p" "$crate_file" | sort | tail -n 1)
case "$last_day_full" in
    0*)
        last_day_no="${last_day_full:1}"
        ;;
    *)
        last_day_no="$last_day_full"
        ;;
esac

echo "$crate: duplicating all lines containing '{Day|day}${last_day_full}', and replacing with '${day_full}'."
sed -E -i "s/^.*(Day|day)${last_day_full}.*$/&\\nMARKER&/" "$crate_file"
sed -E -i "/^MARKER/s/${last_day_full}/${day_full}/g" "$crate_file"
sed -E -i "/^MARKER/s/([^0])${last_day_no}/\1${day_no}/g" "$crate_file"
sed -E -i "s/^MARKER//g" "$crate_file"
