load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "googletest",
    remote = "https://github.com/google/googletest",
    # `commit` and `shallow_since` was given by first specifying:
    #     tag = "release-1.10.0"
    # and then following the debug messages given by Bazel.
    commit = "703bd9caab50b139428cea1aaff9974ebee5742e",
    shallow_since = "1570114335 -0400",
)
